version: "3"

services:
  db:
    image: postgres:12.3
    hostname: db
    env_file:
      - .env

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    image: ${DOCKER_REPOSITORY}/app:${DOCKER_APP_VERSION}
    env_file:
      - .env
    depends_on:
      - db
